<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>birthDate</name>
   <tag></tag>
   <elementGuidId>ceb1e2dc-cd5d-45fc-aa08-730bdb85b02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;patient-search-results-table&quot;]/tbody/tr[1]/td[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '   04 Mar 1994' or . = '   04 Mar 1994')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;04 Mar 1994&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ed2a3244-2019-40a9-ac57-9ed3532936dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   04 Mar 1994</value>
      <webElementGuid>acb1a300-111d-4836-8f37-eeb1f8fcc934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patient-search-results-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]</value>
      <webElementGuid>8f638568-604c-4eaa-9ac7-a9aa936ddb58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='patient-search-results-table']/tbody/tr/td[5]</value>
      <webElementGuid>4ae24e1c-9d8c-4efe-b93e-4961bc326415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/following::td[2]</value>
      <webElementGuid>ff983b52-140e-4279-b7b2-080f653bc362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='irman ramadhan rama'])[1]/following::td[3]</value>
      <webElementGuid>3d4d8197-3de9-445b-8c98-0d39e62cd637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent'])[2]/preceding::td[1]</value>
      <webElementGuid>de9b2e4a-7143-4823-882d-fa560eab5482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='irman ramadhan ZPNWq2sg'])[1]/preceding::td[2]</value>
      <webElementGuid>6cf44279-39a8-47e2-98ea-88e8717fa733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>2458d806-a9a2-4ea2-9897-55ca0af98c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '   04 Mar 1994' or . = '   04 Mar 1994')]</value>
      <webElementGuid>6bcb7c8c-cadb-4373-aab0-12fb98871d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
