<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm (2)</name>
   <tag></tag>
   <elementGuidId>ff57829e-03a2-4534-a265-ac073bdeb719</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete-patient-creation-dialog > div.dialog-content > button.confirm.right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='delete-patient-creation-dialog']/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d09fffa-cb43-48ab-8262-928168cef1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm right</value>
      <webElementGuid>ebed3d7d-5356-445c-9ede-f7e18e45e48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>a4da18f0-4082-4724-952c-f7b4c2277097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-patient-creation-dialog&quot;)/div[@class=&quot;dialog-content&quot;]/button[@class=&quot;confirm right&quot;]</value>
      <webElementGuid>5fd74908-13cc-4e5f-a8cb-5ca79cbac4b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-patient-creation-dialog']/div[2]/button</value>
      <webElementGuid>2ff7cbde-380c-4a64-b314-7ed69d1d0dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason cannot be empty'])[1]/following::button[1]</value>
      <webElementGuid>43ba1949-e162-4598-8013-8f81cc755655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason:'])[1]/following::button[1]</value>
      <webElementGuid>1662cb3d-836a-4081-b683-251dafbe6c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[7]/preceding::button[1]</value>
      <webElementGuid>090534d2-b2dd-465d-89b8-92ccb064e864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/button</value>
      <webElementGuid>60e27eb6-b69a-45aa-a7eb-746404abd4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>fdbc3162-5b00-4586-899e-4cbec43ef5f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
