<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>c5e66db9-3b77-48d7-b5b0-9c43c4faa209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start-visit-with-visittype-confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='quick-visit-creation-dialog']/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af2e8b8c-0a20-4207-9341-f0b2feb0ca26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start-visit-with-visittype-confirm</value>
      <webElementGuid>7bc50903-2b7d-452d-afc3-539d21c968d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirm right</value>
      <webElementGuid>ecb7e2a0-92d2-44b8-a822-bb2a3a6a7a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>73484fb2-a459-4c07-86eb-8f9bd100085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-visit-with-visittype-confirm&quot;)</value>
      <webElementGuid>1a5a716f-b42a-4213-9dbc-c3cc1fea5ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='start-visit-with-visittype-confirm']</value>
      <webElementGuid>70b6b9c2-3a3b-4fa3-9557-1edf3ce80f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quick-visit-creation-dialog']/div[2]/button</value>
      <webElementGuid>18e37873-1738-4701-b309-e49aab0c7292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start a visit'])[1]/following::button[1]</value>
      <webElementGuid>b3e5b3cb-5ffa-472d-96da-41f6b91073d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[7]/preceding::button[1]</value>
      <webElementGuid>46390b44-ea8c-48b1-8903-77e6a43a5b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/button</value>
      <webElementGuid>188700cb-d3e2-476f-a611-73793f21da90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'start-visit-with-visittype-confirm' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>2d3c08f7-c9fe-4d9d-819e-2e53460c5556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
