<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm (1)</name>
   <tag></tag>
   <elementGuidId>33af4a26-2416-4ca0-a965-0a837e31a3dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='registration-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Confirm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4af15ff3-9c18-45ca-a90f-fce503de7b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-submit</value>
      <webElementGuid>75c516c0-8555-4689-b029-3e0cdb5264d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b951b0da-82c9-407c-994a-0e8368c4ce6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submitButton confirm right focused</value>
      <webElementGuid>a3980f45-d97f-4ba8-b91c-668b108b7eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Confirm
                    </value>
      <webElementGuid>afa61cb6-1516-4d6d-ab7b-1e93204cb60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-submit&quot;)</value>
      <webElementGuid>1b221c41-ee7b-4a53-9783-98c417572d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='registration-submit']</value>
      <webElementGuid>9066c672-a138-45f4-a171-6ac652c0a68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmationQuestion']/p/button</value>
      <webElementGuid>7ff79326-758a-4e25-becb-496c12d7a7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birthdate:'])[1]/following::button[1]</value>
      <webElementGuid>c7114b17-f210-487e-aca5-9802d3587a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>11e219f6-8a43-494b-ba5c-d24c8bb93ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/button</value>
      <webElementGuid>0ce8f44d-af68-4ba0-930f-cf9cd9a4b6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'registration-submit' and @type = 'submit' and (text() = '
                        Confirm
                    ' or . = '
                        Confirm
                    ')]</value>
      <webElementGuid>9edd0f22-5b22-4a68-9dff-b703891bed28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
