<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>2cdf8aa6-2438-4ba6-8d42-6dd8ea0b8b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cancelSubmission</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cancelSubmission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cancel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27d4cdce-1057-4795-9bf3-a4b37c605c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelSubmission</value>
      <webElementGuid>04d413f1-c549-403d-bc16-68ac811bc9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancel</value>
      <webElementGuid>b90e3e44-d5a2-4431-8f01-c5f85c9d2f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1bc0eac-60dc-4deb-b5e2-eff03941f988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Cancel
                    </value>
      <webElementGuid>a9b5c0f8-7de0-4fa9-9714-4cf357350590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelSubmission&quot;)</value>
      <webElementGuid>b2fdf832-4b72-49d9-afb5-99bb7f71bf47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cancelSubmission']</value>
      <webElementGuid>83779aa3-9c5f-440d-8b9e-f1d11368c13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmationQuestion']/p[2]/button</value>
      <webElementGuid>a2e2fb1c-1b8d-4d30-8c34-2ba00e20474b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[2]/following::button[1]</value>
      <webElementGuid>d907d9f8-d25e-4592-979c-c5acdfe07610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancel']/parent::*</value>
      <webElementGuid>9408bd3d-96fd-4b62-bdaa-4922d44205a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/button</value>
      <webElementGuid>9e0b1b6e-3fd3-419c-b94b-17d6498c08a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cancelSubmission' and @type = 'button' and (text() = '
                        Cancel
                    ' or . = '
                        Cancel
                    ')]</value>
      <webElementGuid>7131d006-413f-46fe-aefd-d44d88ffa5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
