<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_WEIGHT GRAPH_chart chart-line ng-iso_7fa852</name>
   <tag></tag>
   <elementGuidId>84d88341-7a98-4bfb-944c-8b57fafac4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.chart.chart-line.ng-isolate-scope.chartjs-render-monitor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr7295']/div[2]/obsgraph/div/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>canvas</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>51de2c05-feaa-41df-a5a9-c6e5ef808375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chart chart-line ng-isolate-scope chartjs-render-monitor</value>
      <webElementGuid>2c472ed9-3d12-429e-8c62-5dc895bdce56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>chart-data</name>
      <type>Main</type>
      <value>$ctrl.data</value>
      <webElementGuid>5ab698ff-3270-4aa0-b946-02c18cb945c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>chart-labels</name>
      <type>Main</type>
      <value>$ctrl.labels</value>
      <webElementGuid>20ca3713-76e1-4a54-a442-05feb2115f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>chart-series</name>
      <type>Main</type>
      <value>$ctrl.series</value>
      <webElementGuid>b725ccaf-d701-4022-8249-7c5e28433102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>chart-options</name>
      <type>Main</type>
      <value>$ctrl.options</value>
      <webElementGuid>eb84c4a4-96fa-4beb-a9a7-4809b541d1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>407</value>
      <webElementGuid>46f1ae79-06e5-43d6-872b-bfbe4b26a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>203</value>
      <webElementGuid>d28ec5c3-0c73-40df-a612-32441b13186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr7295&quot;)/div[@class=&quot;info-body&quot;]/obsgraph[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/canvas[@class=&quot;chart chart-line ng-isolate-scope chartjs-render-monitor&quot;]</value>
      <webElementGuid>b43710e0-8f76-4e7a-ad2e-c69e2d05377f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr7295']/div[2]/obsgraph/div/canvas</value>
      <webElementGuid>7fc4a26f-7433-4226-adc3-4ac611583baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>9ca6d2d3-e98c-416d-83fc-c5d78f77d3d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
