<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Outpatient</name>
   <tag></tag>
   <elementGuidId>ffa8c372-eebd-4935-89bb-1860704f595d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.active-visit-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[6]/div[4]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Outpatient&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25a80c46-6dd0-4dc0-9412-509a38371bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-visit-message</value>
      <webElementGuid>db5522c4-3612-4470-954b-3f7b3f6301e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Outpatient
        </value>
      <webElementGuid>f2971678-11c8-4e6a-9d63-13dfbf17e23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;patient-header row&quot;]/div[@class=&quot;secondLineFragments col-12 mt-2 mb-1&quot;]/div[@class=&quot;active-visit-message&quot;]</value>
      <webElementGuid>1194d2e8-86fd-4d9c-9fbe-f605400e2687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[6]/div[4]/div[2]</value>
      <webElementGuid>13aea6ca-ffc8-4577-9107-09e1adb4c45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Visit - 12.Apr.2025, 15:50:30'])[1]/following::div[1]</value>
      <webElementGuid>716d285d-cf04-433f-9a1b-9bc6b10765b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient ID'])[1]/following::div[4]</value>
      <webElementGuid>cc8de052-fc21-473c-9268-26e875c738f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Patient Identifier'])[1]/preceding::div[10]</value>
      <webElementGuid>6ef8acde-de81-4213-85f7-8eb485ebfcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient'])[1]/preceding::div[11]</value>
      <webElementGuid>885ea40c-1646-48c8-93fe-7754190bb153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outpatient']/parent::*</value>
      <webElementGuid>19f24de5-7c3f-4ba9-bc04-3863aa831d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]/div[2]</value>
      <webElementGuid>1b312d3e-141f-4ea9-8b1c-3ababcf0d36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
            Outpatient
        ' or . = '
            Outpatient
        ')]</value>
      <webElementGuid>0b4369b2-5c6f-418b-822e-9d44b09b7712</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
