<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_None (1)</name>
   <tag></tag>
   <elementGuidId>ec28ed7c-283e-4a59-a3b8-1ed0564ad903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#most-recent-encounter-container3225-</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-mostRecentVitals']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0bcf8509-3ba6-4191-b6d1-7afa92deda84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>most-recent-encounter-container3225-</value>
      <webElementGuid>624b81ef-1e9d-4c4b-9beb-b7ba4ba60b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>in</value>
      <webElementGuid>9cd5c10f-fa25-435f-85f6-c173a675bbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&#xd;
            None&#xd;
        </value>
      <webElementGuid>c17332bd-cacf-49ae-90a0-05a20e090c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;most-recent-encounter-container3225-&quot;)</value>
      <webElementGuid>6b745c6f-c689-40e3-b42b-07b94286e3f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='most-recent-encounter-container3225-']</value>
      <webElementGuid>6ae72be8-2ea6-4fe0-a36f-d1eca436543b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-mostRecentVitals']/div[2]/div</value>
      <webElementGuid>26de063d-10e4-451e-ab48-e8890c8bed79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VITALS'])[1]/following::div[2]</value>
      <webElementGuid>7ac7fa41-a662-47bf-bfcf-781891d58a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPOINTMENTS'])[1]/preceding::div[1]</value>
      <webElementGuid>fd7d30a8-016a-404c-bd29-7e781aa320f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[4]/preceding::div[2]</value>
      <webElementGuid>56f2f094-9554-46bb-9e33-4d569d430277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div</value>
      <webElementGuid>2dccaf2f-9e6f-4d90-ba8b-a943cbc68a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'most-recent-encounter-container3225-' and (text() = '
            None
        ' or . = '
            None
        ')]</value>
      <webElementGuid>ce7355ba-b886-48b1-add7-04b1ccecdb62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
