<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Identifier</name>
   <tag></tag>
   <elementGuidId>6639b158-9b1f-449b-9048-704a6e454230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.DataTables_sort_wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='patient-search-results-table']/thead/tr/th/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Identifier&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5143a0c4-048d-449d-be78-79793fb70617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DataTables_sort_wrapper</value>
      <webElementGuid>5879697e-9f8a-43f8-bd31-c2aa6853d257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Identifier</value>
      <webElementGuid>62564e77-0ed8-4c17-bb78-cd2af1f1dada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patient-search-results-table&quot;)/thead[1]/tr[1]/th[@class=&quot;ui-state-default&quot;]/div[@class=&quot;DataTables_sort_wrapper&quot;]</value>
      <webElementGuid>214f1f19-dca4-4dbd-ab3b-2d60680e7159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='patient-search-results-table']/thead/tr/th/div</value>
      <webElementGuid>b8c4ff88-241e-4934-8e32-b0094365fc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Patient Record'])[1]/following::div[7]</value>
      <webElementGuid>7dbd7ddc-1f71-4445-9a75-91be25203308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[1]</value>
      <webElementGuid>c7752ee8-ba04-44e6-9e9e-74f1790edb69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::div[2]</value>
      <webElementGuid>979b284e-2cb5-4b12-9f4e-cdd1740cc5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Identifier']/parent::*</value>
      <webElementGuid>b3901f12-c906-4747-84c9-ad4d1d76e83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div</value>
      <webElementGuid>4fcccb28-40f2-497f-9c1c-2506400a6a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Identifier' or . = 'Identifier')]</value>
      <webElementGuid>962f9c21-c8c6-4351-a912-8b33264d4279</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
