<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Attachments (1)</name>
   <tag></tag>
   <elementGuidId>a4d61ddd-c5a1-43f4-a585-e5817b8dbe59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='attachments.attachments.overallActions.default']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bf99c21-6165-4a51-9809-13841fd887f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-11 col-lg-10</value>
      <webElementGuid>ac5a5f64-f29c-430f-b2f3-8d33f525e4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Attachments
                                                </value>
      <webElementGuid>c1b9b82b-5544-450f-bfdb-c995b5383b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attachments.attachments.overallActions.default&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-11 col-lg-10&quot;]</value>
      <webElementGuid>49385813-c24f-401e-9210-a286ec29c9f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='attachments.attachments.overallActions.default']/div/div[2]</value>
      <webElementGuid>fe4be4c0-85af-4d41-8a87-1a6cd791ae4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Patient'])[1]/following::div[3]</value>
      <webElementGuid>6943799b-c3b0-4c25-af33-2d1d702c361b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Registration Information'])[1]/following::div[6]</value>
      <webElementGuid>ee6c8e18-c15f-4582-a5af-52f8a0990be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::div[2]</value>
      <webElementGuid>1566124a-7e74-4833-a265-ea30cf4add40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[2]/preceding::div[3]</value>
      <webElementGuid>bb9e1c0a-710b-444c-8f97-cf7006923645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attachments']/parent::*</value>
      <webElementGuid>27e5bd53-4fa1-4520-8af6-4d4525fe2859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/div/div[2]</value>
      <webElementGuid>211fd441-8cfe-4c28-8d9a-a94c55a2a78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                                    Attachments
                                                ' or . = '
                                                    Attachments
                                                ')]</value>
      <webElementGuid>27705f22-2490-4e7d-abb7-0eb3e65c04d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
