<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Attachments</name>
   <tag></tag>
   <elementGuidId>f0e830dd-0dcb-4452-8a8c-448533d54ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='attachments.attachments.overallActions.default']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7647727-9a28-4602-8234-cc025411020f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-11 col-lg-10</value>
      <webElementGuid>fd957c2f-04c4-45d0-9985-736872784b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Attachments
                                                </value>
      <webElementGuid>81793a9d-04e3-4299-b28a-91bbcb294a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attachments.attachments.overallActions.default&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-11 col-lg-10&quot;]</value>
      <webElementGuid>4d00071d-b560-46d6-89fe-8ff74f1b0525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='attachments.attachments.overallActions.default']/div/div[2]</value>
      <webElementGuid>b1260a10-9b93-4005-be0a-080775df5e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Patient'])[1]/following::div[3]</value>
      <webElementGuid>4024f9b5-075a-4132-b4f0-f8301dda17bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Registration Information'])[1]/following::div[6]</value>
      <webElementGuid>f7635fbb-4951-459c-bdd1-c45c94d4a508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::div[2]</value>
      <webElementGuid>d92dbd2f-0b54-464d-9397-2cf00b9780c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[2]/preceding::div[3]</value>
      <webElementGuid>78614a02-01ee-4ce2-bf7a-7b5f685e9f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attachments']/parent::*</value>
      <webElementGuid>74f7f811-f6f2-4ab7-8470-69eb8f5d5441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a/div/div[2]</value>
      <webElementGuid>ca6556de-6a9a-4710-a97c-e5f1ba39a54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                                    Attachments
                                                ' or . = '
                                                    Attachments
                                                ')]</value>
      <webElementGuid>e5e51cca-0dcf-4e24-9c66-29e773fdf91e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
