<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_None</name>
   <tag></tag>
   <elementGuidId>d8428ce2-4d8b-4dc0-a536-445d61a2b5d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#most-recent-encounter-container3225-</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '&#xd;
            None&#xd;
        ' or . = '&#xd;
            None&#xd;
        ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-mostRecentVitals']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7143f488-7e41-4ad7-a1f6-7a6a9b582bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>most-recent-encounter-container3225-</value>
      <webElementGuid>9caa2dd2-3083-4a4e-a41d-e9a0fe355f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>in</value>
      <webElementGuid>ef4f3a50-aa59-4b30-9f90-cea8a1279308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&#xd;
            None&#xd;
        </value>
      <webElementGuid>6b627309-3539-493b-a012-6e9124512fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;most-recent-encounter-container3225-&quot;)</value>
      <webElementGuid>a0eaff93-b65a-4519-987f-35510e72dc3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='most-recent-encounter-container3225-']</value>
      <webElementGuid>48b71380-7831-483e-983e-8bd4bf8ff0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-mostRecentVitals']/div[2]/div</value>
      <webElementGuid>9650a7a5-169f-4792-8340-d2d373cde123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VITALS'])[1]/following::div[2]</value>
      <webElementGuid>ceda32bc-06ef-4934-9a14-8d6e4203b08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPOINTMENTS'])[1]/preceding::div[1]</value>
      <webElementGuid>eff1069d-5994-4ff1-8b4a-7455ba5c86a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[4]/preceding::div[2]</value>
      <webElementGuid>7c453e2f-5c68-495e-b510-3565ecead28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div</value>
      <webElementGuid>6add3feb-6ead-4c0d-b78c-20d12bcc7c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'most-recent-encounter-container3225-' and (text() = '
            None
        ' or . = '
            None
        ')]</value>
      <webElementGuid>09f4f95a-9d4c-46d0-bf6b-65b9ae62ed1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
