<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Address</name>
   <tag></tag>
   <elementGuidId>c9e30675-3d95-47b4-945e-4c2fabb9b811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contactInfoContent']/div/span/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.contact-info-inline.labeled > span > em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>6d5ebe45-f1e4-4d9c-bba8-acd4795910fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>02ec7e33-e276-4907-a0ba-3511beeb431c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactInfoContent&quot;)/div[@class=&quot;contact-info-inline labeled&quot;]/span[1]/em[1]</value>
      <webElementGuid>4a0bfd03-72c5-4b32-b3c2-6a095375b812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contactInfoContent']/div/span/em</value>
      <webElementGuid>516ffcf0-455e-4ad7-a48f-6102a0594fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Contact Info'])[1]/following::em[1]</value>
      <webElementGuid>1259e8e3-c8e1-40b6-a746-455e646c3747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telephone Number'])[1]/preceding::em[1]</value>
      <webElementGuid>46dc9c1c-a76d-473f-839c-257cd3ec3751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::em[2]</value>
      <webElementGuid>379627ec-3226-49a9-afc0-70bd812f152f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Address']/parent::*</value>
      <webElementGuid>161d1653-3405-4b0a-986b-67acab4572c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/em</value>
      <webElementGuid>86ebb86c-4095-467a-a880-b2b463c693e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'Address' or . = 'Address')]</value>
      <webElementGuid>13f52c3f-56fc-4470-9ee1-439d5b16a860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
