<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_ALLERGIES (1)</name>
   <tag></tag>
   <elementGuidId>bd33d446-9bb4-4557-b315-641efd6def88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.info-section.allergies > div.info-header > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[9]/div/div/div[2]/div[5]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>60bc4885-0a57-4a23-8866-d7377c1e7b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALLERGIES</value>
      <webElementGuid>d8e439a7-91f9-4884-9da3-7b107389de63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;dashboard clear row&quot;]/div[@class=&quot;col-12 col-lg-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;info-section allergies&quot;]/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>710b7d86-0672-4c5d-ae98-92f25722437f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[9]/div/div/div[2]/div[5]/div/h3</value>
      <webElementGuid>944f8680-be14-4f6d-b0ab-937cb8ad16df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load more'])[1]/following::h3[1]</value>
      <webElementGuid>965c070d-8fec-48e8-b0df-7374b5ebcc85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATTACHMENTS'])[1]/following::h3[1]</value>
      <webElementGuid>675bf158-6c5c-415f-b281-006e129cb8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[1]/preceding::h3[1]</value>
      <webElementGuid>ce9f18cc-e825-4459-bcfa-141ee38a0242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Actions'])[1]/preceding::h3[1]</value>
      <webElementGuid>ef07fc88-0040-47f6-9477-37552b2b8af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALLERGIES']/parent::*</value>
      <webElementGuid>ab193841-852e-46b0-a7e1-2e1af241181d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div/h3</value>
      <webElementGuid>e103ba43-cad4-4970-8441-b2dd18b600ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'ALLERGIES' or . = 'ALLERGIES')]</value>
      <webElementGuid>5b72499a-968a-48f5-b741-9be940cefa8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
