<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_CONDITIONS</name>
   <tag></tag>
   <elementGuidId>e33cd54d-163d-48b7-92a9-53a7d309d825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[9]/div/div/div[2]/div[3]/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.info-section.conditions.ng-scope > div.info-header > h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>d7cab8a8-a132-47cc-ae0b-2ff7015baa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONDITIONS</value>
      <webElementGuid>650bb1d3-e0ee-4770-a6ca-ec667a5a40e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;dashboard clear row&quot;]/div[@class=&quot;col-12 col-lg-9&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;info-section conditions ng-scope&quot;]/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>5230e5ad-5f57-4676-a11d-7fd52312c8d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[9]/div/div/div[2]/div[3]/div/h3</value>
      <webElementGuid>a088f203-85c0-4459-af17-16597456cb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[7]/following::h3[1]</value>
      <webElementGuid>025af787-990d-4fd7-98a1-25c2bc115901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::h3[1]</value>
      <webElementGuid>c4913f67-6554-4b9a-9fed-40d36819aa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove Condition'])[1]/preceding::h3[1]</value>
      <webElementGuid>7b2ba882-cb04-45a0-98f3-3a5b294ad2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONDITIONS']/parent::*</value>
      <webElementGuid>9a3a9b33-ab82-4f89-815c-51c90c2864ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/h3</value>
      <webElementGuid>07de470b-a7ad-4cf1-801d-ee25ddf77db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'CONDITIONS' or . = 'CONDITIONS')]</value>
      <webElementGuid>a6a7a688-1b02-4922-b1a4-0d386c930bba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
