<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_DIAGNOSES (1)</name>
   <tag></tag>
   <elementGuidId>c1fb4841-45b0-49da-b828-51e1be7621ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.info-header > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-diagnosesList']/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>0b18fe9d-9ddc-4b0e-8f21-81106a84e820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIAGNOSES</value>
      <webElementGuid>f8667140-a8d2-4de8-b803-0e4c48055cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-diagnosesList&quot;)/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>d5e20465-5e0c-4563-8027-7ef39cefd270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-diagnosesList']/div/h3</value>
      <webElementGuid>55810478-28ee-45d3-91aa-66b74700431d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::h3[1]</value>
      <webElementGuid>8ead9715-5272-49a3-a067-72bd48e4920a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[4]/following::h3[1]</value>
      <webElementGuid>04b841cd-6e54-4c94-ba74-7d16080aa2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None in the last 730 days'])[1]/preceding::h3[1]</value>
      <webElementGuid>4bcb0a2c-2908-4655-9e2f-97af8de12750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LATEST OBSERVATIONS'])[1]/preceding::h3[1]</value>
      <webElementGuid>c1f3ef86-c42f-473b-b6a2-aed9d7191669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIAGNOSES']/parent::*</value>
      <webElementGuid>1c25e0f3-10ba-4aeb-b0da-192b4597947b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/h3</value>
      <webElementGuid>c1bc6f30-3f10-4da4-96ba-92e4cef0bcc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'DIAGNOSES' or . = 'DIAGNOSES')]</value>
      <webElementGuid>7a79bdeb-7dda-4aa5-8c28-44471b4e005e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
