<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_DIAGNOSES</name>
   <tag></tag>
   <elementGuidId>3e0393c7-db21-4e2c-b285-eafa1f05539c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-diagnosesList']/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.info-header > h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>1070a7af-dab2-43d5-a1cc-ccf2892b61eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DIAGNOSES</value>
      <webElementGuid>f9ee41f8-9536-4d77-a15b-204874c7e6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-diagnosesList&quot;)/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>231eb759-da1d-4955-a512-a05eeb1e591c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-diagnosesList']/div/h3</value>
      <webElementGuid>7d8acf86-9e19-49cb-aea4-3f3a42184f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::h3[1]</value>
      <webElementGuid>e5cc091c-5ba8-44b8-9d1c-10c59f66bc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[4]/following::h3[1]</value>
      <webElementGuid>cc45f9d7-385d-4360-b0be-daa669e59422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None in the last 730 days'])[1]/preceding::h3[1]</value>
      <webElementGuid>30a9b2de-b577-4e66-990b-6c79a3ee3c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LATEST OBSERVATIONS'])[1]/preceding::h3[1]</value>
      <webElementGuid>780df085-08d5-4d3b-9518-b07dec08d6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DIAGNOSES']/parent::*</value>
      <webElementGuid>10e46bb8-cb3a-4202-9f1c-93219217d286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/h3</value>
      <webElementGuid>a690a272-f55f-4f97-9e3a-b1c1c02329a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'DIAGNOSES' or . = 'DIAGNOSES')]</value>
      <webElementGuid>fb4c495e-1e8c-448f-916e-4635251fb44b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
