<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_FAMILY (1)</name>
   <tag></tag>
   <elementGuidId>ef956252-3322-4e16-b1f9-ac57b4ea9d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coreapps-fr8021 > div.info-header > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='RECENT VISITS'])[1]/following::h3[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>deb5d7cd-1264-4104-911e-2b45fd80dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAMILY</value>
      <webElementGuid>06a4892e-30ca-419d-a4da-a9aff5e4d927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr8021&quot;)/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>f2264895-74ae-4a4e-b5c2-d2406114f705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr8021']/div/h3</value>
      <webElementGuid>88600bcc-29c2-4750-a43b-66ac2e452340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECENT VISITS'])[1]/following::h3[1]</value>
      <webElementGuid>ccc7a36d-f7a6-4310-9e71-a6ead59171e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[4]/following::h3[2]</value>
      <webElementGuid>359bfc3a-9380-45d9-84e8-5198df29cdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to remove this relationship?'])[1]/preceding::h3[1]</value>
      <webElementGuid>e03be88d-5c2b-4fbb-b235-9f8e7f81407c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new relationship'])[1]/preceding::h3[1]</value>
      <webElementGuid>b9e3d25e-fea2-4277-abd4-3604ba2c909e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FAMILY']/parent::*</value>
      <webElementGuid>50bda729-29cb-454f-b722-1299b2f1363a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/h3</value>
      <webElementGuid>4a7d9490-575a-4f25-aed4-1277eec7ecb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'FAMILY' or . = 'FAMILY')]</value>
      <webElementGuid>74a1c229-d7da-4c5f-ba20-3e3eb9710e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
