<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Pulse</name>
   <tag></tag>
   <elementGuidId>0ab2cf63-d529-44f4-af0d-d0b8005f97b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>fieldset:nth-of-type(5) > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='vitals']/fieldset[5]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Pulse&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>d8680289-7850-45ab-ace3-a0b46ec0d043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pulse</value>
      <webElementGuid>42dc0ebb-4126-4b28-8af7-d8746b5dcfb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vitals&quot;)/fieldset[5]/h3[1]</value>
      <webElementGuid>62681054-6f54-4202-af17-ba41a7a1a57c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='vitals']/fieldset[5]/h3</value>
      <webElementGuid>1ec6a24f-8695-4084-969b-bc70e0ae7128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulse'])[1]/following::h3[1]</value>
      <webElementGuid>5bffa16a-12a9-44f9-94df-2dd95c0e1952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='°C'])[1]/following::h3[1]</value>
      <webElementGuid>e5c1dc85-578e-445b-9225-2851472b4725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/min'])[1]/preceding::h3[1]</value>
      <webElementGuid>1f82e58a-7b9b-4435-9d12-84866b770332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respiratory rate'])[1]/preceding::h3[1]</value>
      <webElementGuid>7659abc3-c11e-4f13-9617-835812b414a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/h3</value>
      <webElementGuid>11c6d102-6479-4a12-a6b6-aaf705908f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Pulse' or . = 'Pulse')]</value>
      <webElementGuid>3d5828a5-b153-4b57-b1f0-15999dfcd8e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
