<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_VITALS (1)</name>
   <tag></tag>
   <elementGuidId>ddd7a256-9530-4bc6-baae-a0fef4af4341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coreapps-mostRecentVitals > div.info-header > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-mostRecentVitals']/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>ffcb101d-47ab-4bcd-be77-9639d7c6e809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VITALS</value>
      <webElementGuid>a43247b7-96a1-4960-820c-9d7e302a3289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-mostRecentVitals&quot;)/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>11a1486a-cdcf-4df7-990f-8b54c111102f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-mostRecentVitals']/div/h3</value>
      <webElementGuid>9c5d10d3-8ef3-46e1-bd0f-3760986c6e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[1]/following::h3[1]</value>
      <webElementGuid>a652cd49-cabe-4fe2-9393-1bb5b8cd5b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[3]/preceding::h3[1]</value>
      <webElementGuid>62ba29ee-6211-4a22-a435-7e73a3cfe781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPOINTMENTS'])[1]/preceding::h3[1]</value>
      <webElementGuid>64068553-9c74-44a7-ac3a-563378d8f033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VITALS']/parent::*</value>
      <webElementGuid>80ea864b-179e-4012-9ac4-4655720cbb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[5]/div/h3</value>
      <webElementGuid>0090a236-56a1-4532-826b-bd40bb941abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'VITALS' or . = 'VITALS')]</value>
      <webElementGuid>16acf0e8-04c0-41b4-93fb-eb0a42f04a52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
