<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_VITALS (2)</name>
   <tag></tag>
   <elementGuidId>357c09c4-07f4-4db7-9708-a7448c6ae5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#coreapps-mostRecentVitals > div.info-header > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-mostRecentVitals']/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;VITALS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>1b7ba4c2-f78a-4ba6-b4b2-09264dd596d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VITALS</value>
      <webElementGuid>3f129e0a-610a-4cbd-8133-9da92d59ae0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-mostRecentVitals&quot;)/div[@class=&quot;info-header&quot;]/h3[1]</value>
      <webElementGuid>fa49b318-5f52-42de-9491-c3b0a6b33825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-mostRecentVitals']/div/h3</value>
      <webElementGuid>574b0998-f750-4e0e-800d-579f1368d2e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[1]/following::h3[1]</value>
      <webElementGuid>8b41b01b-562f-456c-9ea0-de46b6255a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When?'])[1]/preceding::h3[1]</value>
      <webElementGuid>98d18ae3-1b35-4e4e-881c-70ed9dcacf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When?'])[2]/preceding::h3[1]</value>
      <webElementGuid>a91913d9-d892-410b-b7a1-33145be1a540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VITALS']/parent::*</value>
      <webElementGuid>e08bf75b-3ac7-43e0-9205-292383035aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[5]/div/h3</value>
      <webElementGuid>6d25c7f9-216b-4716-81d7-cbd91c1cc9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'VITALS' or . = 'VITALS')]</value>
      <webElementGuid>fcb1c2b2-5203-4bb1-8b53-a8cc71b54d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
