<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Capture Vitals for Patient_patient-search (1) (1)</name>
   <tag></tag>
   <elementGuidId>5038a9bc-3927-4719-89a1-74be04f7afee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#patient-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='patient-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search by ID or Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f388fafb-eb7e-431d-96f7-9a38f426abf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5dd8f5af-f08d-46a9-9328-5b9bb8ee763d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18a5a39e-cdb6-4716-b00b-9461a28123d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>patient-search</value>
      <webElementGuid>880fb3d2-cddd-4f53-a7a9-447d777a84db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by ID or Name</value>
      <webElementGuid>91cd3850-00a6-457c-b719-8ae071e9ad7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f58835f7-9c73-4fa8-8d26-ae8abaf3fa03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patient-search&quot;)</value>
      <webElementGuid>ac337d3d-b162-488e-b02a-a450b39b4457</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='patient-search']</value>
      <webElementGuid>17918a73-e8de-487d-af60-e82b30d2b383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patient-search-form']/input</value>
      <webElementGuid>ec09eb48-2265-43ea-97ac-72d17c9169cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>077fee7a-b9ec-4eab-a784-a683ebea439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'patient-search' and @placeholder = 'Search by ID or Name']</value>
      <webElementGuid>15716980-9488-4432-b9ce-ae42904972d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
