<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Arterial blood oxygen saturation (pul_224004 (1)</name>
   <tag></tag>
   <elementGuidId>c5cadd04-38ae-4229-acf4-5a6b819cac6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29463552-22ab-4f29-b317-17990a6ea014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>894a3683-6f2c-4e55-9fc0-e377ec995588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>30e1f694-1b5b-4667-875e-ecb1489b19b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w22</value>
      <webElementGuid>b70b81e9-b0a8-46ac-bc77-60be3ab07478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w22</value>
      <webElementGuid>49e6a21c-917e-494c-912f-40c06299a128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>47ba252b-45aa-42ee-a5c9-2ef067188ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100.0</value>
      <webElementGuid>38153bf9-542e-43ce-bed1-d1409144e826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>integer numeric-range focused</value>
      <webElementGuid>47a569f9-f6ae-4ae9-acbf-5fd57c0a07ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>cd8c84d2-8ea2-4277-a0a6-52230a94ac17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w22&quot;)</value>
      <webElementGuid>9c35bd41-2555-4bfb-9979-49a5d5a561e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w22']</value>
      <webElementGuid>e704e4d8-1dda-4c3a-86af-537876d7f156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='o2_sat']/input</value>
      <webElementGuid>18e372d5-14d0-4703-baf0-901b2ee5560f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[8]/p/span/input</value>
      <webElementGuid>066ef20f-d6a7-4105-a38e-6da892a725cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w22' and @name = 'w22']</value>
      <webElementGuid>0be39cf6-141c-4ae2-b734-55b74dde234d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
