<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_givenName</name>
   <tag></tag>
   <elementGuidId>ca4d2b27-1591-4a61-85b5-970c178697d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'givenName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=''givenName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fr5813-field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05793d11-73e6-4ecf-a728-e38f258c9e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e0f1171-198f-46ee-a229-75cb48a29fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>givenName</value>
      <webElementGuid>e8861c59-2392-48e0-bdb1-6931cc62a530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required focused ui-autocomplete-input</value>
      <webElementGuid>24972f79-a15c-474c-ab9d-00fb91af3e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>470129e7-46fd-4d5c-9f56-dea1d5bb7518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr5813-field']</value>
      <webElementGuid>3bbc938f-572d-4863-8c0c-7ea4be04f4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-name']/div/p/input</value>
      <webElementGuid>362c1314-50ed-4926-8b81-cd72fcdaca13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2e385fc1-9ab7-4645-9d80-90192ac4ab9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr5813-field' and @name = 'givenName']</value>
      <webElementGuid>c5f6edb7-fc6d-4326-aeaf-875eebe01b05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
