<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reason_delete-reason</name>
   <tag></tag>
   <elementGuidId>326f7059-8045-4516-88f0-ebe68c2b479f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#delete-reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='delete-reason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Reason:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b44c9c8c-28ce-4ec5-8a7f-a9147f88ff76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dee66ea7-2bf0-4a1d-ad0d-7ce9e177d8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete-reason</value>
      <webElementGuid>12f4d3d2-2ea7-4a04-bc39-f2f15a9e15fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-reason&quot;)</value>
      <webElementGuid>cc03e456-bd42-435b-a689-779c0c9bbc58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='delete-reason']</value>
      <webElementGuid>04456dc8-85f1-4fb6-a4b3-97194b0b3712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete-patient-creation-dialog']/div[2]/input</value>
      <webElementGuid>d3007b53-0ec4-4a74-a3b3-4953e236cd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/input</value>
      <webElementGuid>9fc37e23-832a-430f-ae4a-5e2cfc5cc6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'delete-reason']</value>
      <webElementGuid>c80b0a63-65f9-4fe6-aceb-9c16112f9dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
