<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight (kg)_w10 (1)</name>
   <tag></tag>
   <elementGuidId>c43d86d7-ebde-4c4e-aea3-6b67bd84f876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eea42ae4-aa59-4124-97af-2851033ef229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a06db22b-341d-407e-8caf-953ee3d26131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a43a3605-0a9a-4bea-9044-36db8f340cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w10</value>
      <webElementGuid>c3c77975-2976-4dfe-b693-5caa7b0b04b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w10</value>
      <webElementGuid>7758ad5d-33d5-4cb6-959d-4f8b2eb467e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>0d0bf14b-60e6-4fa3-b555-01ceb097e3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>250.0</value>
      <webElementGuid>ea3709d1-c93b-4eb7-8018-fd5a6bb2a768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number numeric-range focused</value>
      <webElementGuid>4c16f0a5-da94-4126-93fc-e4045e761255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>99986f65-02d3-493d-9c4e-9bf83980cd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w10&quot;)</value>
      <webElementGuid>1f721356-fd40-4ca9-bbf7-6e34dda02290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w10']</value>
      <webElementGuid>9809d554-22d4-443f-92d9-9d3826c84939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='weight']/input</value>
      <webElementGuid>ee38ecfe-fb20-4540-95e2-41d4e33f5b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/span/input</value>
      <webElementGuid>5f59798b-9610-4f57-8243-a0a1d82b62d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w10' and @name = 'w10']</value>
      <webElementGuid>340dc321-4a9f-4594-933a-72c3a9335071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
