<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Who is the patient related to_person-_c8514e</name>
   <tag></tag>
   <elementGuidId>e1c97b50-7c19-4295-bd87-892765a22bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.person-typeahead.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f2b74e5-dac4-4db7-97a0-f8de39144739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bab9d4b5-0f1b-42a8-beb9-ae08423fa527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>person-typeahead ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>e0726080-1c50-47af-b2de-2963d30911fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Person Name</value>
      <webElementGuid>d3c56217-31d2-4c7e-9efd-f62400ef175f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>relationship.name</value>
      <webElementGuid>287c8007-dea1-4225-8178-837e67b1cade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead</name>
      <type>Main</type>
      <value>person as person.display for person in getPersons($viewValue) | limitTo:5</value>
      <webElementGuid>c720b1d9-66c2-4baf-9dd8-d90f9165096a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a1c72f45-b9fb-4abe-b003-78dd6ac9fce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-on-select</name>
      <type>Main</type>
      <value>selectPerson($item, $index)</value>
      <webElementGuid>f205f7e0-6ee4-47fe-86d7-af0fb0d20e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationship&quot;)/p[@class=&quot;left&quot;]/input[@class=&quot;person-typeahead ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>2923482d-f76a-43d6-988f-3220e08b78dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[15]</value>
      <webElementGuid>7185cf16-52dc-41d3-ae8e-19129d499167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='relationship']/p[2]/input</value>
      <webElementGuid>e60ac220-259c-4e85-a3ef-3d25e496091f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p[2]/input</value>
      <webElementGuid>aa3a30e0-8630-42a4-87bd-ba58c57a9a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Person Name']</value>
      <webElementGuid>4fd80541-2d33-4ced-90fb-315086d9cbba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
