<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Who is the patient related to_person-_c8514e_1</name>
   <tag></tag>
   <elementGuidId>c45a6c62-76f3-4bde-83eb-304bc328a851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[17]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.person-typeahead.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1951f662-fcc0-4012-80ff-79cc12c1345f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d4aef7d-07b2-4851-ada8-8000412e9af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>person-typeahead ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>0cd7909c-8220-4f37-a7fe-f4f435574a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Person Name</value>
      <webElementGuid>011e1811-5818-4072-bb78-c0f51b95d620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>relationship.name</value>
      <webElementGuid>4110f11e-32e1-438d-9af0-e4242cf51894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead</name>
      <type>Main</type>
      <value>person as person.display for person in getPersons($viewValue) | limitTo:5</value>
      <webElementGuid>9789b573-1318-42a6-aa1c-920e5b8c952a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d9c74242-cefa-421e-abcb-1f20dba1bbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-on-select</name>
      <type>Main</type>
      <value>selectPerson($item, $index)</value>
      <webElementGuid>5c231cbd-88c0-448c-9840-cb652d524d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationships-info&quot;)/div[1]/fieldset[@id=&quot;null&quot;]/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;relationship&quot;]/p[@class=&quot;left&quot;]/input[@class=&quot;person-typeahead ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>be2f1f2c-cf82-463d-bfc5-80ec212db87a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[17]</value>
      <webElementGuid>1155de3b-8435-4d7f-8b70-7eb4d8af82ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='relationship']/p[2]/input)[3]</value>
      <webElementGuid>1d1aa001-1992-4587-ba62-787909025f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p[2]/input</value>
      <webElementGuid>105a270c-d68d-4ac3-8f60-c75cbc98fd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Person Name']</value>
      <webElementGuid>71520234-ad51-49ce-88c1-39f0bfea2827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
