<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s the patient phone nu_867169</name>
   <tag></tag>
   <elementGuidId>be75236a-5fc9-416d-97de-e96704deb923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'phoneNumber']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fr2467-field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fr2467-field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9fc682d-1702-49f6-b87b-f34799da1616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84a77d9a-069c-487e-95f4-ec0890c47828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>54a044c9-e409-4cf4-b01a-1f8667023296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone focused</value>
      <webElementGuid>16b73f72-d605-42b0-bb29-8e13188d434e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr2467-field&quot;)</value>
      <webElementGuid>91095a2a-07f5-48b0-918e-457efc820143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr2467-field']</value>
      <webElementGuid>9129f6a3-3109-45bc-8871-6246c65fe3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel']/p/input</value>
      <webElementGuid>e273a17c-52ce-4481-b726-f8c15c0dc5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/input</value>
      <webElementGuid>1d9cf0ae-7e3d-49d1-87a8-117254a3b423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr2467-field' and @name = 'phoneNumber']</value>
      <webElementGuid>c84b3d07-8011-46cf-9014-4608ceaa27c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
