<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height (cm)_w8 (1)</name>
   <tag></tag>
   <elementGuidId>749419cc-fa60-4b62-aadf-12f3a4ff3679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>790cae1f-6bc3-45e4-b4f1-3edab2332734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6445dd3-4543-45f6-a5f5-e49e38e21585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8a66c2c7-65b4-43a3-9977-de25d28bb237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w8</value>
      <webElementGuid>b9ac0b2f-94c8-4ef3-8655-461a2ed47314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w8</value>
      <webElementGuid>81b39e37-93a1-40f9-9edf-ee07705a4b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>10.0</value>
      <webElementGuid>d7a58c14-1319-4c19-b664-d5a5a157769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>272.0</value>
      <webElementGuid>cec71043-3c90-4d22-9d50-3c7adb3f7217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number numeric-range focused</value>
      <webElementGuid>92d36e9b-ada0-4544-aa49-0a8426e9c0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>3d61514e-5039-4818-bc14-a0d46bef4558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w8&quot;)</value>
      <webElementGuid>dc172ffb-d889-423b-abef-b10d29002aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w8']</value>
      <webElementGuid>7a7adb11-a872-4583-b6ce-68f51feee9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='height']/input</value>
      <webElementGuid>98eaf80d-4a5a-4186-82f1-ba4abe8be4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span/input</value>
      <webElementGuid>7f73fb76-0098-4a58-b14d-d7ce445e95c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w8' and @name = 'w8']</value>
      <webElementGuid>4a9e973f-d20a-43be-975d-1bab968920e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
