<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_familyName</name>
   <tag></tag>
   <elementGuidId>0dca96b0-cb84-4e73-b841-0fee63a354f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'familyName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fr5175-field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fr5175-field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d257c726-d1ac-43fe-a6ca-fb8804503d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0af393a7-a852-4b4c-939b-cdc2a8133ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>c04cb3b8-4307-4f22-8053-eef72e36cb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required ui-autocomplete-input</value>
      <webElementGuid>c0f74e16-eb88-43bc-9c11-6104d0d242c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a9d0726-f5d5-43fe-ba18-101abf1bfc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr5175-field&quot;)</value>
      <webElementGuid>3f66d90e-133c-4d2b-ad54-2f98b0f4ce0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr5175-field']</value>
      <webElementGuid>516baf99-28ed-42eb-b74f-23f1bdc03b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-name']/div/p[3]/input</value>
      <webElementGuid>8c0596fc-6434-431e-9202-ca7d3837b011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>bb5d1be7-3867-4ac2-9af6-ee690f98697b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr5175-field' and @name = 'familyName']</value>
      <webElementGuid>b4165082-d897-4148-bcd4-37a64c1fd924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
