<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Arterial blood oxygen saturation (pul_224004</name>
   <tag></tag>
   <elementGuidId>d5660459-8501-4d86-80a4-bb39d861a7c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w22</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w22']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6580458d-f182-489b-be11-f23a3fa32685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59579dd5-cf1a-48fd-88ad-b61ca19c20da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2d7948aa-55c2-426f-ab7f-9fbba97f5087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w22</value>
      <webElementGuid>a3f163b2-a664-41d5-be5f-342075db0087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w22</value>
      <webElementGuid>debcb2eb-a6c1-42cc-8e8e-751d805a69e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>f13326a5-f2fa-4777-b8b5-e19daad063db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100.0</value>
      <webElementGuid>8d1d193c-0c3e-4b4e-99ac-438b9cb0df70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>integer numeric-range focused</value>
      <webElementGuid>bbf207d0-d8a7-490a-b82e-b3e05ca2c886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>380dfd0c-fc95-4ae9-9e7e-1cc837dcdb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w22&quot;)</value>
      <webElementGuid>68233ca5-c1db-447e-a4d5-11fd2d469735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w22']</value>
      <webElementGuid>6c69dd16-cd68-4978-9357-251cae43e3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='o2_sat']/input</value>
      <webElementGuid>2f8df8a6-6b73-4c8b-b802-72d7adb7f379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[8]/p/span/input</value>
      <webElementGuid>a56ebfd8-bb33-4269-95dd-0f8f6c9151f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w22' and @name = 'w22']</value>
      <webElementGuid>3957091a-cec1-431b-8584-69d1135f6be2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
