<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Save_cancel focused (1)</name>
   <tag></tag>
   <elementGuidId>61279741-8978-464c-a4ab-e46237c1c1f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.cancel.focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;No&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1036205b-fbce-4201-865f-aaad8e9514a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ff2e6187-3bee-477e-97b7-c42b8a5247e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>84960804-b838-4d60-87b8-bb517b606c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancel focused</value>
      <webElementGuid>ba14d043-451b-48c1-8f12-a55008dc101c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>3ea10ace-a56e-4fc6-bda9-38bcf5bfab21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmationQuestion&quot;)/p[2]/input[@class=&quot;cancel focused&quot;]</value>
      <webElementGuid>b88fcdbd-10fd-4621-b35a-33c2315fcfd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='No']</value>
      <webElementGuid>dd17f392-9c41-4df4-892d-f4e88b52a488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmationQuestion']/p[2]/input</value>
      <webElementGuid>46f6dee0-f89c-4e54-8b89-d1998c8c1007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>accaad69-c6f9-4e7c-a71c-02ce5886e1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>cc82a394-0a4f-4e4c-a834-43790d1908f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
