<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Blood Pressure_w18</name>
   <tag></tag>
   <elementGuidId>7c997aa1-4a13-47f5-857e-b8485411bfe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;w18&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aae13f85-637b-45a8-a231-9e4c31201276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f392a441-710d-4dbf-b617-4f809ed5639e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b31b62e9-cc26-49f1-b599-507c8aeb8d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w18</value>
      <webElementGuid>f8227bfd-557b-4f4d-9f0d-f290fe2b26a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w18</value>
      <webElementGuid>cc9850fb-c619-4a2d-bca6-8a659846593e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>62f7c972-e873-4039-8d57-7fef886d34e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>250.0</value>
      <webElementGuid>0e69bb95-59cd-431b-be26-cd6b105d2bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>integer numeric-range expected focused</value>
      <webElementGuid>2dfa46c1-b12b-42be-a628-ed70f2c67ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>2b54c6b4-310f-4a2f-925c-da41f82bbe66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w18&quot;)</value>
      <webElementGuid>bdbad330-3045-4286-a5d7-8dd011a7c65e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w18']</value>
      <webElementGuid>bf003e76-bc0e-4b4e-b962-8de8de191ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bp_systolic']/input</value>
      <webElementGuid>664c3257-1369-469c-b04b-91ce09b4951a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[7]/p/span/input</value>
      <webElementGuid>9644ceb9-a266-493a-9948-cfad8218ba29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w18' and @name = 'w18']</value>
      <webElementGuid>098e5773-6ecb-47c4-9912-8c3b07282c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
