<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pulse_w14 (1)</name>
   <tag></tag>
   <elementGuidId>24a9d38b-417b-428b-bd0b-e516db7a7187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e331f788-65a2-47d6-a5a7-a26a7fc83a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae0aa2b7-d6e5-44d2-8e49-0f8711903051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>448d23bf-ec75-4fda-bbc0-882b2f306d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w14</value>
      <webElementGuid>7aebff63-cb99-492b-a1cc-9dc588cc6134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w14</value>
      <webElementGuid>eb372c19-b049-46cd-9a0b-856b2c3247e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>ca9aeeec-85fb-4a42-b8cc-a428505374f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>230.0</value>
      <webElementGuid>bf494355-874b-4694-830a-632d05e99f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>integer numeric-range focused</value>
      <webElementGuid>0155e598-c508-4dad-8be5-b04f5a70ad86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>554a6927-c326-422d-ad3e-0fe3cb76db04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w14&quot;)</value>
      <webElementGuid>c44bd9ca-a0a2-4e7a-b65b-46315d6a0e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w14']</value>
      <webElementGuid>cf6f691b-15c1-4866-a162-05483b86d2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='heart_rate']/input</value>
      <webElementGuid>bbb97950-3e8c-409f-a1e4-9d07ecaec1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/p/span/input</value>
      <webElementGuid>64c2936d-549d-4fb3-bcb2-e5f251eac7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w14' and @name = 'w14']</value>
      <webElementGuid>9a7662b2-c3c6-402b-8592-8204679e2d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
