<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle_middleName (1)</name>
   <tag></tag>
   <elementGuidId>12357908-f53c-4591-86d4-77f644c62599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fr8723-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='demographics-name']/p[2]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'middleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Middle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfe0aab4-b75b-4e96-be29-c2afff8c8516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e78fb166-a9fe-4a3d-90e0-43843c7daa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr8723-field</value>
      <webElementGuid>36f50210-b2f0-4a19-9633-247432559ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>c34e0026-8b77-4c30-a6f2-4a2a49ae33fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ramadhan</value>
      <webElementGuid>772be4aa-fff9-44d5-9ec6-110da09f51d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focused</value>
      <webElementGuid>149ec538-0645-44f8-ad9d-128386a37d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr8723-field&quot;)</value>
      <webElementGuid>dd7138ff-0b9a-4bd8-9172-019f67b9f918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr8723-field']</value>
      <webElementGuid>e624b321-306e-4ae0-95a4-afb867a405b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-name']/p[2]/input</value>
      <webElementGuid>9ed93313-82ee-4b08-8150-38898c0d00f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>3ca210ac-59c2-4621-af4e-abeec2ddb17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr8723-field' and @name = 'middleName']</value>
      <webElementGuid>861903f1-444e-4336-b5c6-2d07b1e25407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
