<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Blood Pressure_w18 (1)</name>
   <tag></tag>
   <elementGuidId>bd9f1dae-225c-4fb0-b8e2-51cba48d769e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;w18&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db4becd6-88f1-4e78-97da-ad607ce54eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be7a3a72-c10e-484f-b377-b36cae4b0b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>55ce6e3a-661c-4a00-a180-36037f6e404b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w18</value>
      <webElementGuid>fed6ab45-3a9c-457b-b2fc-01888fd97981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>w18</value>
      <webElementGuid>458c4fdb-21b8-4093-bd67-c5efb7492d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>fbe7306b-6ef6-4f54-8360-abfe89632428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>250.0</value>
      <webElementGuid>33173ec5-c753-4a13-a04a-25d1342a1f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>integer numeric-range expected focused</value>
      <webElementGuid>7937df58-da19-4a33-953f-eb65e7b77591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>49164407-7cd1-4ca3-97e4-e37c2c27105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w18&quot;)</value>
      <webElementGuid>d5ad738f-af00-4351-a5ac-84830a7ec9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w18']</value>
      <webElementGuid>39dfee9a-95ed-4d38-b906-76b0f5e33002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bp_systolic']/input</value>
      <webElementGuid>833c14a5-818a-4e2c-8b45-108f2ee96be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[7]/p/span/input</value>
      <webElementGuid>c69700ff-e4e2-4d4c-a05f-8f5d4d29cf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w18' and @name = 'w18']</value>
      <webElementGuid>ab62ed95-1ce9-49fc-9ded-7e22f7f2d932</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
