<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Visits</name>
   <tag></tag>
   <elementGuidId>6a8a096e-f63e-4059-bb13-5d621914db77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-state-default.ui-corner-top.ui-tabs-active.ui-state-active.ui-state-hover.ui-state-focus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[9]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Visits&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b711826a-af70-45fc-8ca2-3b9d0e723db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-state-default ui-corner-top ui-tabs-active ui-state-active ui-state-hover ui-state-focus</value>
      <webElementGuid>c5d13e13-c8c4-469c-9af6-7fcce0319cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>7e500aad-9525-4067-8068-8a1cb9345bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d63b5afb-9db8-41dd-af1b-e83e0d70d664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>visits</value>
      <webElementGuid>3e5c6011-337d-4ba1-a03e-822e8df67c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ui-id-1</value>
      <webElementGuid>fddfed2c-953a-46c5-b810-4a6c91d4a722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d193773b-5dce-4bde-bec8-0aa312789f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                
                    Visits
                
            </value>
      <webElementGuid>6d6203d5-4dfa-47ed-a83e-bae7adfb9056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;tabs ui-tabs ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;dashboard-container&quot;]/ul[@class=&quot;ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all&quot;]/li[@class=&quot;ui-state-default ui-corner-top ui-tabs-active ui-state-active ui-state-hover ui-state-focus&quot;]</value>
      <webElementGuid>6b73ce47-8de6-4f46-ba5c-8018ee9c3d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[9]/div/ul/li</value>
      <webElementGuid>013df327-6c1f-43e2-910a-f2c7c8d60b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Patient'])[1]/following::li[1]</value>
      <webElementGuid>1bf79f80-5868-4fc1-a81c-e72dc590fc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Registration Information'])[1]/following::li[2]</value>
      <webElementGuid>82029cee-1eb9-4548-8461-37cff72b0825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appointments'])[1]/preceding::li[1]</value>
      <webElementGuid>33cbc13e-92d7-4bd5-93ee-9ad83de4284a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/ul/li</value>
      <webElementGuid>0802d270-7ea6-4258-9d7e-6a05bec1ac86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
                
                    Visits
                
            ' or . = '
                
                    Visits
                
            ')]</value>
      <webElementGuid>59ce313a-b98c-4763-8882-a94c6e612437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
