<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Arterial blood oxygen saturation (pulse o_5bf421</name>
   <tag></tag>
   <elementGuidId>76ee0a54-dbdb-4e92-a00b-23a3cf00de21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Arterial blood oxygen saturation (pulse oximeter): 99 %&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>41055b28-fe13-4cd2-8535-14c98102b1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arterial blood oxygen saturation (pulse oximeter): 99 %</value>
      <webElementGuid>4250cb2d-2447-47fd-b988-f18a0075e9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[8]</value>
      <webElementGuid>2ad90ef6-9dfe-4914-81d9-769a686f8ffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p[8]</value>
      <webElementGuid>a98a3381-b195-411b-bbb5-f7047a9396a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure:'])[1]/following::p[1]</value>
      <webElementGuid>ba5c9dbf-15db-4479-a8a4-6cf81d094070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/min'])[4]/following::p[2]</value>
      <webElementGuid>5fedea9f-fea4-431e-97d6-27cf84e48d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]</value>
      <webElementGuid>19a27f77-bdc5-47e2-b226-0651b87a5f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Arterial blood oxygen saturation (pulse oximeter): 99 %' or . = 'Arterial blood oxygen saturation (pulse oximeter): 99 %')]</value>
      <webElementGuid>d3f48f9b-e479-4e7d-b9e1-b906db02ac06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
