<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Arterial blood oxygen saturation (pulse o_5bf421 (1)</name>
   <tag></tag>
   <elementGuidId>a64f7256-386f-417d-b2cc-80aa60ec15bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Arterial blood oxygen saturation (pulse oximeter): 99 %&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6446fc8e-2f82-4ddc-95ad-f25d9f983951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arterial blood oxygen saturation (pulse oximeter): 99 %</value>
      <webElementGuid>8fc62268-a2ea-4e1f-973b-d51b5196d1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[8]</value>
      <webElementGuid>40c15f94-cb09-43f9-b25f-7f0aa3b13266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p[8]</value>
      <webElementGuid>a94f8382-ed87-43fa-b567-010c960890a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure:'])[1]/following::p[1]</value>
      <webElementGuid>723daf57-2e5b-4fdc-95fa-a11908d4886e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/min'])[4]/following::p[2]</value>
      <webElementGuid>0d670e26-8d0c-403a-9147-ea6d70f5e8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]</value>
      <webElementGuid>49a19ba9-4190-4e2a-b6cb-ad9bff6f2acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Arterial blood oxygen saturation (pulse oximeter): 99 %' or . = 'Arterial blood oxygen saturation (pulse oximeter): 99 %')]</value>
      <webElementGuid>286b404f-5676-4cde-b1a5-d405540afaf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
