<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Height (cm) 165 cm (1)</name>
   <tag></tag>
   <elementGuidId>2117a9bd-760f-4d98-9739-3a7c1a48f8fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Height (cm): 165 cm&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6549a0f1-bea3-403a-a124-eaed096dd4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Height (cm): 165 cm</value>
      <webElementGuid>576d6832-845c-4be5-a757-e32d8daaca52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[1]</value>
      <webElementGuid>ca554dfa-3548-4106-b0c2-dc0992b05c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p</value>
      <webElementGuid>95968240-dcd5-4533-8535-1499a1796bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm submission?'])[1]/following::p[1]</value>
      <webElementGuid>77fff9ef-92c2-4ea5-b9a4-a7c32f5ad548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::p[1]</value>
      <webElementGuid>1c6b2c8c-3f86-43bc-81eb-a50cdc0af18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='165']/parent::*</value>
      <webElementGuid>5c3167ab-3d9d-4c33-825e-cdb942cb4f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>4a4b3001-d189-40b0-af95-8093b8418c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Height (cm): 165 cm' or . = 'Height (cm): 165 cm')]</value>
      <webElementGuid>86b0ff83-9d1f-407e-834d-bce3208d7b24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
