<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Weight (kg) 70 kg (1)</name>
   <tag></tag>
   <elementGuidId>07d8de22-ce56-4c15-860b-0eaecc8f33c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > p:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Weight (kg): 70 kg&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>90a31012-b379-40f6-bafa-f39535427a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weight (kg): 70 kg</value>
      <webElementGuid>e383ca26-c788-4dec-9a00-0cda3034ed80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[2]</value>
      <webElementGuid>268e042d-a804-4c72-b0e8-96a7aa7f4710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p[2]</value>
      <webElementGuid>e5179ec6-11b9-4457-8e4f-e9fc0297a903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cm'])[2]/following::p[1]</value>
      <webElementGuid>fda4785f-e375-4d8c-a63d-c30024218cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Height (cm):'])[1]/following::p[1]</value>
      <webElementGuid>b222bba7-47df-4498-ad0b-57eec037ee6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='70']/parent::*</value>
      <webElementGuid>9d6c5095-ecf3-4afc-9b24-7d91861e30af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p[2]</value>
      <webElementGuid>a0df3a71-5f88-4594-a2e5-52d5fc9ef157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Weight (kg): 70 kg' or . = 'Weight (kg): 70 kg')]</value>
      <webElementGuid>7173a1eb-887e-440f-b3a9-1c01c092855d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
