<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_165</name>
   <tag></tag>
   <elementGuidId>2dc28590-1508-4ae5-8414-f7634ec7b480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#height > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='height']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#height >> internal:text=&quot;165&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e78c8eb-c946-4044-bc3b-b909c4e0fb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>609b9824-eaf8-4fc5-b262-c4b6a23a6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>165</value>
      <webElementGuid>589b93df-bc61-45e4-858d-f8e041a962bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>aea83ccb-577b-4921-b6e4-1797dd026832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='height']/span</value>
      <webElementGuid>b585ac69-3d9f-4bb1-9daf-da9a1d8a7b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Height (cm)'])[2]/following::span[2]</value>
      <webElementGuid>8e3a93e9-6212-48e8-bb3e-4ca73b486a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Height (cm)'])[1]/following::span[2]</value>
      <webElementGuid>34ed8278-1928-43f5-b194-3a8d99f41308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cm'])[1]/preceding::span[1]</value>
      <webElementGuid>6526eefd-b339-4f5b-896d-c8c6d8e32fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[2]/preceding::span[2]</value>
      <webElementGuid>3a42321a-5760-4c99-b7aa-214af1325db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/p/span/span</value>
      <webElementGuid>8f00f342-0930-4569-bb78-f7d48e2cd68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '165' or . = '165')]</value>
      <webElementGuid>932c5ba8-13a8-40c9-8f5e-160599df36cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
