<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_70_1</name>
   <tag></tag>
   <elementGuidId>db34a923-8b8b-425a-926b-4da4736a4117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weight > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='weight']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#weight >> internal:text=&quot;70&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ab82d9b9-2d66-4d76-a336-080462e4f874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>a30c405a-5cc4-4cec-8359-7df053268f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>c7fcb3d6-43ac-42f9-977e-4271c5989f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>9069ecb6-3417-4157-bdcb-8d92e4a14d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='weight']/span</value>
      <webElementGuid>8c974f5a-8564-4ef9-9b46-62a20c4cec06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[3]/following::span[2]</value>
      <webElementGuid>67e8e42a-a5db-42d0-b4e4-97ddee0a0168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[2]/following::span[2]</value>
      <webElementGuid>5b00db7d-6c4c-4f6e-9499-10b05219757e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kg'])[1]/preceding::span[1]</value>
      <webElementGuid>45f30e96-d110-4023-b13e-ff1cc3f8d2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Calculated) BMI'])[1]/preceding::span[2]</value>
      <webElementGuid>dff237e2-0962-4686-b490-7d5ba8857559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/span/span</value>
      <webElementGuid>d5428272-295f-4922-8fb2-367af1dcbbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '70' or . = '70')]</value>
      <webElementGuid>bfc958d9-b992-4b85-ab0f-254ab225a516</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
