<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_today_1_2</name>
   <tag></tag>
   <elementGuidId>c5b13bd6-052f-4a31-ac06-ee41e16814bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr2146']/div[2]/latestobsforconceptlist/ul/li[3]/div/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;today&quot;s >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>140528d3-02d5-4156-b8ac-2032c5d4a192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>59eb41e7-734e-4a72-80a4-e8efd53076e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                today
            </value>
      <webElementGuid>010d57f9-d526-40fb-96c9-58a0ee77f6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr2146&quot;)/div[@class=&quot;info-body&quot;]/latestobsforconceptlist[@class=&quot;ng-isolate-scope&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/div[1]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>a68d289f-e76a-4a0a-9f67-6be53428b5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr2146']/div[2]/latestobsforconceptlist/ul/li[3]/div/span[3]</value>
      <webElementGuid>58457c5e-6b7d-4c2a-9703-2691014c343e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[2]/following::span[3]</value>
      <webElementGuid>5fc21250-aaa0-452a-980c-dc671cffa7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[4]/preceding::span[3]</value>
      <webElementGuid>3864d803-f45f-4aeb-bfb5-f052b21b0fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span[3]</value>
      <webElementGuid>c5392bee-a104-46e1-8c9e-f2a7f03c6996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                today
            ' or . = '
                today
            ')]</value>
      <webElementGuid>72e0bd21-0ae3-4c1d-9f10-4d550d470309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
