<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_087777777777</name>
   <tag></tag>
   <elementGuidId>04f75c5f-cf48-40dd-a964-692d6c361b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='coreapps-telephoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#coreapps-telephoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>518080b8-fafb-47f4-be37-1f6c157ebcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coreapps-telephoneNumber</value>
      <webElementGuid>bf4e12e9-6158-4cc2-9fe4-a6f12820bdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            087777777777
        </value>
      <webElementGuid>c8dcf1f1-da5e-4b7b-822e-2c9477936592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-telephoneNumber&quot;)</value>
      <webElementGuid>744559eb-32a6-4447-be6f-67e58183813b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='coreapps-telephoneNumber']</value>
      <webElementGuid>32b0406d-5a67-4959-8e57-d420330e2eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contactInfoContent']/div/span[2]/span</value>
      <webElementGuid>f7966844-3d1c-4224-81c7-0d96a670f416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::span[2]</value>
      <webElementGuid>87dc6f42-5a8b-4823-931e-3bda54a4ad90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telephone Number'])[1]/preceding::span[1]</value>
      <webElementGuid>dea8687b-41ef-4154-973c-8f1108dfe7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::span[1]</value>
      <webElementGuid>b9c8d4a1-c4b5-4d3e-8996-153e204f5ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='087777777777']/parent::*</value>
      <webElementGuid>7f66e416-fef0-4e02-ac15-d65dbc14dea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]/span</value>
      <webElementGuid>45be583d-effb-42ac-a01e-6cfc4cb07a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'coreapps-telephoneNumber' and (text() = '
            087777777777
        ' or . = '
            087777777777
        ')]</value>
      <webElementGuid>964e6544-a02e-4c93-942a-1de1ea5d643c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
