<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100_1_2</name>
   <tag></tag>
   <elementGuidId>44511043-308f-4f1c-aeae-c005f6606a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bp_systolic > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bp_systolic']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bp_systolic >> internal:text=&quot;100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee0fde61-35c8-4e03-add3-5380628bbf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>8f6848cc-fc0a-4f5b-b8fc-72f575a851eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>263180fe-c01b-4d0a-be54-04cf00b25aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bp_systolic&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>684c196a-47a6-4813-a05a-8699146afcef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bp_systolic']/span</value>
      <webElementGuid>c3b11932-d7c4-4080-b002-e3b12a783fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure'])[2]/following::span[2]</value>
      <webElementGuid>490b459c-405e-4bd5-9046-7bf6c6475267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure'])[1]/following::span[2]</value>
      <webElementGuid>df73f6a7-276d-4a42-ac04-ae752b289fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arterial blood oxygen saturation (pulse oximeter)'])[1]/preceding::span[3]</value>
      <webElementGuid>bf0743bc-3f50-4e54-997b-ea21f940e476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arterial blood oxygen saturation (pulse oximeter)'])[2]/preceding::span[3]</value>
      <webElementGuid>70a6ac19-9405-4376-9139-6901220b5d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[7]/p/span/span</value>
      <webElementGuid>29390aad-ed1a-44bf-9559-e51166bf1fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '100' or . = '100')]</value>
      <webElementGuid>07414708-2fd2-42a1-9726-77e10d9c112f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
