<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25.7 (1)</name>
   <tag></tag>
   <elementGuidId>4c3dd88e-cef4-4289-893f-e059be1342e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calculated-bmi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='calculated-bmi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;25.7&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>740fe266-4325-4fbc-a326-d634ed23ca6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculated-bmi</value>
      <webElementGuid>90686c2c-316b-4244-88b6-ad2666c72d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25.7</value>
      <webElementGuid>3b85510d-b903-4951-95eb-ef61d72de9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculated-bmi&quot;)</value>
      <webElementGuid>8b731d66-3111-40a6-b5b8-9350d8b3af81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='calculated-bmi']</value>
      <webElementGuid>ec5f9338-134d-4023-a517-6c7102eba28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='calculated-bmi-wrapper']/span</value>
      <webElementGuid>5f893e84-4957-4f76-b097-d8506e5a50ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you record a weight and height, we will calculate the BMI'])[1]/following::span[2]</value>
      <webElementGuid>eadd2421-f605-4afe-9649-1d24476c841a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Calculated) BMI'])[2]/following::span[3]</value>
      <webElementGuid>be80ca8c-6c43-4d30-bd8a-d463842b3f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature (c)'])[1]/preceding::span[1]</value>
      <webElementGuid>32a5ae2a-4427-474e-8aca-f95c3dcb5a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature (c)'])[2]/preceding::span[1]</value>
      <webElementGuid>11d0d0cd-2953-4277-aca8-5ff7540cc071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25.7']/parent::*</value>
      <webElementGuid>e595e054-31e8-425e-a7ee-fe0e2f7a2f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/span[2]/span</value>
      <webElementGuid>73f157c6-c0ab-487b-b0ad-a5ba3fa909bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'calculated-bmi' and (text() = '25.7' or . = '25.7')]</value>
      <webElementGuid>cd313295-cd8d-4d16-a9ff-032ae044695e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
