<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Show Contact Info</name>
   <tag></tag>
   <elementGuidId>84f50e52-8486-493e-886b-1bd454826f1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='coreapps-showContactInfo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#coreapps-showContactInfo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d8c92f57-9c22-4d77-a118-9ecd769d04ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>coreapps-showContactInfo</value>
      <webElementGuid>5dc33644-07f5-4393-9e35-be81f3e3e34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show</value>
      <webElementGuid>30a0a158-3de7-4c4c-addf-12ac84bb68a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show Contact Info</value>
      <webElementGuid>9c5278ab-c004-4cfd-bca9-49336e8a8a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-showContactInfo&quot;)</value>
      <webElementGuid>57f3e2b4-87dc-431b-bac8-532b3996fa2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='coreapps-showContactInfo']</value>
      <webElementGuid>3c12e84c-62be-4aa4-835c-b63e7f7e767c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='patient-header-contactInfo']/span</value>
      <webElementGuid>b701a259-f249-4f65-8daf-34e8ba6de7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::span[1]</value>
      <webElementGuid>1ca77f81-1faa-4f8d-b8ac-d0fbdb62b777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide Contact Info'])[1]/preceding::span[1]</value>
      <webElementGuid>04a39c50-6465-4dc9-ab54-26ead17f3ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show Contact Info']/parent::*</value>
      <webElementGuid>26072b33-bb83-4148-9224-3b9f956e272b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>ed9cfd4f-799c-4044-a8f7-9a10fccbf795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'coreapps-showContactInfo' and (text() = 'Show Contact Info' or . = 'Show Contact Info')]</value>
      <webElementGuid>39430001-056c-415b-9f7c-2ee8ca4bda64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
