<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_27 (1)</name>
   <tag></tag>
   <elementGuidId>82a508ae-c430-4421-9942-a2da3c87f7b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#temperature > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='temperature']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#temperature >> internal:text=&quot;27&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee1a83a5-5ef4-4d4e-af63-18eabff29cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>8fc52a02-efba-41e4-a59e-ca6f182b34c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>8896076a-32b4-4a49-8ef3-51708513e1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;temperature&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>dc083e13-f7f8-4640-be9f-ce572096ef29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='temperature']/span</value>
      <webElementGuid>e702667f-5a36-4e43-9917-b82807668483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature (c)'])[2]/following::span[2]</value>
      <webElementGuid>8baf1c7e-3283-478f-b1e8-b777967f71b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature (c)'])[1]/following::span[2]</value>
      <webElementGuid>a1cd246e-cca4-4f4b-8033-1e86ac052299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='°C'])[1]/preceding::span[1]</value>
      <webElementGuid>5ee08a35-bfb5-4ee8-9f0a-fb63ab773a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pulse'])[1]/preceding::span[2]</value>
      <webElementGuid>f63128dc-583c-43fd-b313-9f7ee5c052f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/p/span/span</value>
      <webElementGuid>6fc7f1c7-750f-49fb-a2eb-2486b3c79fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '27' or . = '27')]</value>
      <webElementGuid>b691115a-6170-4fb5-b6cd-0b104d10b4f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
