<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_25.7</name>
   <tag></tag>
   <elementGuidId>be0a2f99-729b-4745-b0e0-fdd42e72cb10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calculated-bmi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='calculated-bmi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;25.7&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef93181d-a4c2-4f7d-8410-6012b58b474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculated-bmi</value>
      <webElementGuid>1ddf09b6-bb5c-4fe1-ab17-3ac5dc76c583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25.7</value>
      <webElementGuid>553c3965-d5dc-4b68-b0eb-967f2e00112f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculated-bmi&quot;)</value>
      <webElementGuid>bb7cd476-51db-44c7-8f9b-158f505e5000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='calculated-bmi']</value>
      <webElementGuid>aee0bedc-1c94-4962-b816-47cf0a618f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='calculated-bmi-wrapper']/span</value>
      <webElementGuid>c011d69c-6a34-4cf3-ad2b-2da8a44a8551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you record a weight and height, we will calculate the BMI'])[1]/following::span[2]</value>
      <webElementGuid>b7b973a3-d9b8-4610-bdda-195b2982eec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Calculated) BMI'])[2]/following::span[3]</value>
      <webElementGuid>340db42a-b21d-4ea2-bb10-f0acd7baaadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature (c)'])[1]/preceding::span[1]</value>
      <webElementGuid>6d10a3c0-49bc-4cfd-ab57-60dd8cc86213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temperature (c)'])[2]/preceding::span[1]</value>
      <webElementGuid>b255c862-ba73-4709-aa43-0bfa1318dec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25.7']/parent::*</value>
      <webElementGuid>62d7c1cf-6e7a-4192-845f-d745c5e1eb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/span[2]/span</value>
      <webElementGuid>bc213590-3240-4af8-a09c-3e126342abee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'calculated-bmi' and (text() = '25.7' or . = '25.7')]</value>
      <webElementGuid>8dbbb455-b957-4032-82ee-b49a93727e4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
