<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_99</name>
   <tag></tag>
   <elementGuidId>52a5dd75-ea75-4be7-9919-b8c1ebe9f8d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#respiratory_rate > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='respiratory_rate']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#respiratory_rate >> internal:text=&quot;99&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>48f3aa76-68d3-4d50-b4c7-8f2910216837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>3de4ad5f-0412-45bf-a15f-a35ac5030ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>04c6c35e-b3dc-4429-bcaf-0845cc6c151d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;respiratory_rate&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>ae425345-7e18-4f71-af9e-eb8becc572f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='respiratory_rate']/span</value>
      <webElementGuid>669a6700-fc29-45d3-b44a-65529b2758ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respiratory rate'])[2]/following::span[2]</value>
      <webElementGuid>559549fb-32fa-4d0e-9de2-2938097458b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Respiratory rate'])[1]/following::span[2]</value>
      <webElementGuid>b0940cbb-ca69-4e86-a933-a6b6876b5299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/min'])[2]/preceding::span[1]</value>
      <webElementGuid>028d3c4c-cf98-4675-b325-8966fc866786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure'])[1]/preceding::span[2]</value>
      <webElementGuid>ff7e0ba7-56e5-4bed-90a5-0c51339470e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='99']/parent::*</value>
      <webElementGuid>d0e4a36f-6eb4-49fc-a4dc-5bf6eec391f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[6]/p/span/span</value>
      <webElementGuid>97dc0ffa-d539-49ef-8da6-df12b203e58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '99' or . = '99')]</value>
      <webElementGuid>39c6df49-ec72-45ef-b288-fda0713aed67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
