<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_today (1)</name>
   <tag></tag>
   <elementGuidId>dce6f0ab-f16e-4e87-9f1d-72dfc3ccf23f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr1661']/div[2]/latestobsforconceptlist/ul/li/div/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;today&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>651d4b2b-3b59-4c86-9078-d29e33d0fdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>7e22dc48-3903-40de-88aa-3919beb4c800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                today
            </value>
      <webElementGuid>9c5bca7c-352a-487a-8db1-0dd265328b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr1661&quot;)/div[@class=&quot;info-body&quot;]/latestobsforconceptlist[@class=&quot;ng-isolate-scope&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/div[1]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>17df226a-bbf0-4698-898e-857769230a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr1661']/div[2]/latestobsforconceptlist/ul/li/div/span[3]</value>
      <webElementGuid>4cc8b946-37ea-4815-b252-f08c3003ec75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LATEST OBSERVATIONS'])[1]/following::span[3]</value>
      <webElementGuid>5b671f2e-1241-46fc-8d5c-5734441a69e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[2]/preceding::span[3]</value>
      <webElementGuid>d6f73f81-c470-481d-9a09-c523145b2751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='today']/parent::*</value>
      <webElementGuid>75757127-0a27-4410-b8c8-3ee776a73e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span[3]</value>
      <webElementGuid>ccf21372-7b11-4a0c-a445-0d3c2948143d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                today
            ' or . = '
                today
            ')]</value>
      <webElementGuid>845f9939-04e2-4d1b-a543-039418a73388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
