<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100LDG</name>
   <tag></tag>
   <elementGuidId>9028f2b7-7313-4190-81c9-a78a758bd067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;content&quot;)/div[@class=&quot;patient-header row&quot;]/div[@class=&quot;identifiers mt-2 col-12 col-sm-5 col-md-4&quot;]/div[@class=&quot;float-sm-right&quot;]/span[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[6]/div[2]/div/span&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.float-sm-right > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0efdda7-48d0-44f9-ad73-45186f35bbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100LDG</value>
      <webElementGuid>328b9575-0c50-4a8e-b702-2896337e86fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;patient-header row&quot;]/div[@class=&quot;identifiers mt-2 col-12 col-sm-5 col-md-4&quot;]/div[@class=&quot;float-sm-right&quot;]/span[1]</value>
      <webElementGuid>9a2f2292-6b71-4d9d-9136-03500f6db63b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[6]/div[2]/div/span</value>
      <webElementGuid>70cb2118-a42b-4a90-822e-4516520873a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient ID'])[1]/following::span[1]</value>
      <webElementGuid>93f30f58-1df3-4594-890b-35b557c1da09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/following::span[1]</value>
      <webElementGuid>9a323d79-f51f-46fd-9c49-e1d88cbc0477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Patient Identifier'])[1]/preceding::span[6]</value>
      <webElementGuid>ead85fcc-c194-4932-8e77-c35d8f92f9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient'])[1]/preceding::span[6]</value>
      <webElementGuid>5bd1c2a4-e26d-4aed-b28f-9f04f0dc0bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100LDG']/parent::*</value>
      <webElementGuid>ae983ac9-c47d-4446-8c27-d2395257d771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>334255f4-0e7a-4e0c-8532-f634b84fb8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '100LDG' or . = '100LDG')]</value>
      <webElementGuid>eac9d290-a647-4373-96db-64fad2328562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
