<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100 (1)</name>
   <tag></tag>
   <elementGuidId>3b995321-42aa-4299-979e-fb024b33efb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ng-scope > span.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='obsTable']/tbody/tr/td[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#obsTable >> internal:text=&quot;100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>848bf334-ba58-4e85-a4f9-e3ba19c1d971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>cellElem.className</value>
      <webElementGuid>092333f0-6bba-46fb-8f29-7bf6adb1c727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>859a6690-f1df-40fe-812b-23a746105f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3b5b4459-94dc-46fb-b9d7-240527ab2e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;obsTable&quot;)/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;ng-scope&quot;]/span[@class=&quot;ng-scope&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>b01f6be8-624e-4645-9776-a6bf92018540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='obsTable']/tbody/tr/td[2]/span/span</value>
      <webElementGuid>4b438dbc-9e42-4065-a9c1-fbd298ebd58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WT'])[1]/following::span[3]</value>
      <webElementGuid>30ef401a-f6d3-424e-8bde-9a53036ea830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temp (c)'])[1]/following::span[3]</value>
      <webElementGuid>9ab38862-6b12-4e4a-b409-e9ce6f6e8dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[2]/preceding::span[6]</value>
      <webElementGuid>0d9d7543-3a7f-42d5-9217-1999fb2a27d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/span</value>
      <webElementGuid>975f879a-a970-4ef0-9379-1b795aeb0ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '100' or . = '100')]</value>
      <webElementGuid>45ea97da-517c-440d-acac-790d1ed46359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
