<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_99_1 (1)</name>
   <tag></tag>
   <elementGuidId>c53414e5-df41-49a8-b6b4-2ff4b6e3effa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#o2_sat > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='o2_sat']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;99&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>18c26908-ef8c-472f-abaf-810bae98c0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>4122035e-e6ae-4325-919e-5de40b9ecc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>80a4cd18-2275-48dc-abfa-d3967e9f4b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;o2_sat&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>17acf5e7-c9ee-494c-bd5c-4e64829b3154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='o2_sat']/span</value>
      <webElementGuid>d6e439d5-2e14-4982-8382-4df2fed4a426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arterial blood oxygen saturation (pulse oximeter)'])[2]/following::span[2]</value>
      <webElementGuid>039cd288-7a8b-4930-9966-e719abfabc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arterial blood oxygen saturation (pulse oximeter)'])[1]/following::span[2]</value>
      <webElementGuid>c5cf32b8-7ab0-41bc-9fb3-d034bd51be2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/preceding::span[1]</value>
      <webElementGuid>e0e92151-7684-4784-85a7-de3d5ee56eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPOINTMENTS'])[1]/preceding::span[2]</value>
      <webElementGuid>b1c101e3-99bf-4c30-8e7b-c215f60a92c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[8]/p/span/span</value>
      <webElementGuid>8ab38d6f-bdb4-462a-a784-c58a9c6b7bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '99' or . = '99')]</value>
      <webElementGuid>ba3ec294-4bf4-4012-83c0-a95fd050d1c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
