<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_165 (1)</name>
   <tag></tag>
   <elementGuidId>7805b001-537c-4eac-94a5-afa1cb3eb9e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#height > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='height']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#height >> internal:text=&quot;165&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ef81ebd-00a4-4213-9110-cb58baf55dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>8da942f0-28be-4065-a735-7a37a4feec3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>165</value>
      <webElementGuid>a14ae86b-6ca6-465e-93ca-edb3881b1428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>055de9d7-116e-4788-af82-c714f813ca6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='height']/span</value>
      <webElementGuid>e2055b0c-81c9-4661-ac24-a8add580a3de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Height (cm)'])[2]/following::span[2]</value>
      <webElementGuid>59e13e04-91e8-44c6-babf-4d7c2708f5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Height (cm)'])[1]/following::span[2]</value>
      <webElementGuid>0f6e2d18-bb4e-41ad-bf08-7aac2a5a80b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cm'])[1]/preceding::span[1]</value>
      <webElementGuid>b90c757f-e7f9-4cbe-9b91-837ba250bb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[2]/preceding::span[2]</value>
      <webElementGuid>73286f11-b4e8-4cf5-a64b-f89ce4fcb9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/p/span/span</value>
      <webElementGuid>432bd26f-1b39-4b41-ac46-f4d487b5b55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '165' or . = '165')]</value>
      <webElementGuid>20b3c3a3-db7b-4d4a-a06a-9d82fe7e3049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
