<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_today_1_2_3</name>
   <tag></tag>
   <elementGuidId>654f0348-e887-4bc7-840f-b55747146001</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr2146']/div[2]/latestobsforconceptlist/ul/li[4]/div/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;today&quot;s >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e153acbe-8f8e-445a-a25c-3b362276b9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>9ffb5b6c-5105-41b1-97fd-f23384230236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                today
            </value>
      <webElementGuid>46e69463-2875-491e-a65a-d2191b4bff38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr2146&quot;)/div[@class=&quot;info-body&quot;]/latestobsforconceptlist[@class=&quot;ng-isolate-scope&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/div[1]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>7bbabb50-66bb-44dd-a1a1-092c101b1e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr2146']/div[2]/latestobsforconceptlist/ul/li[4]/div/span[3]</value>
      <webElementGuid>bf6b00cc-0639-4af9-815c-3faabb8d367b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[3]/following::span[3]</value>
      <webElementGuid>f409a10f-53eb-4772-afb1-222d4848b876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[5]/preceding::span[3]</value>
      <webElementGuid>4cb918fd-202c-44eb-9ebd-d1d4572f451e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span[3]</value>
      <webElementGuid>65bfa8d2-e075-460d-abda-637e7bec7e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                today
            ' or . = '
                today
            ')]</value>
      <webElementGuid>3267f6c1-2295-4236-9a16-a9aeaee38f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
