<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_100_1_2 (1)</name>
   <tag></tag>
   <elementGuidId>9ad595b1-a5c5-43ba-ae7e-a3f6b4fd6dd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bp_systolic > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bp_systolic']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bp_systolic >> internal:text=&quot;100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>832b07d2-b256-4d31-98e9-abcb19cbd24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>031d2f26-afb2-4c50-abaf-96a9788b4ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f4e1a4e7-43dc-4db4-b50e-249664d1fe29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bp_systolic&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>e12c84ac-74be-4c8d-b5fc-e451b1609f60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bp_systolic']/span</value>
      <webElementGuid>eb8596d4-1494-4ee5-a8cc-ef18f47915a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure'])[2]/following::span[2]</value>
      <webElementGuid>9459a201-2262-4cdf-9af1-34e16f847b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blood Pressure'])[1]/following::span[2]</value>
      <webElementGuid>58b33689-3a76-4637-b31b-df4bee9fe5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arterial blood oxygen saturation (pulse oximeter)'])[1]/preceding::span[3]</value>
      <webElementGuid>174adee2-0f96-473b-86cd-c4a59f12ea27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arterial blood oxygen saturation (pulse oximeter)'])[2]/preceding::span[3]</value>
      <webElementGuid>7255051a-7754-4539-914b-cc6617341ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[7]/p/span/span</value>
      <webElementGuid>38bacd26-4971-4e2e-9fa4-fc5314f91333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '100' or . = '100')]</value>
      <webElementGuid>b0481b8b-d65c-4c2b-9a3a-eb2eddc10fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
