<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_70_1 (1)</name>
   <tag></tag>
   <elementGuidId>66574df0-fcbf-4fe0-8307-d0fe5ec3a15d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weight > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='weight']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#weight >> internal:text=&quot;70&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d525a00-a3bd-473f-97d6-5c6d4cbdd802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>f0bf7ceb-4118-49c5-a24e-7f785764f4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>0d109e30-6d76-47df-9ea7-8fc55dcbf20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight&quot;)/span[@class=&quot;value&quot;]</value>
      <webElementGuid>fae2c939-e3a3-45db-88b0-6f1daa1880b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='weight']/span</value>
      <webElementGuid>b4045125-5c4d-441b-87d2-5ff95588764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[3]/following::span[2]</value>
      <webElementGuid>c6ee9576-5c85-4e27-8b02-5f49b597e10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight (kg)'])[2]/following::span[2]</value>
      <webElementGuid>578f4de5-dfb5-45d5-9acc-b113ccf8c5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kg'])[1]/preceding::span[1]</value>
      <webElementGuid>033ba49e-991f-43e9-8ff9-4951a3387440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Calculated) BMI'])[1]/preceding::span[2]</value>
      <webElementGuid>7d66d180-5f51-45a2-ba71-4a355279ca74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/span/span</value>
      <webElementGuid>b78da260-4ad9-4275-a4d0-0ee3f350ab93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '70' or . = '70')]</value>
      <webElementGuid>c5d78e30-9809-46f8-8363-14a881146117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
