<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rama (1)</name>
   <tag></tag>
   <elementGuidId>5723e5b3-8ae3-4865-b3de-15269dd44b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.PersonName-familyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[6]/div/div/div/h1/span[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4aa0365-cd35-4e71-8882-ecb58681a07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PersonName-familyName</value>
      <webElementGuid>d3c7906a-2705-48e1-b0bd-1df11f7b28ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                rama
                            </value>
      <webElementGuid>99e01c20-1263-441c-9e89-072a77c679b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;patient-header row&quot;]/div[@class=&quot;demographics col-12 col-sm-7 col-md-8&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-sm-auto&quot;]/h1[@class=&quot;mt-0 mb-2 name&quot;]/span[@class=&quot;labeled&quot;]/span[@class=&quot;PersonName-familyName&quot;]</value>
      <webElementGuid>5133fa36-8d1f-44e5-add8-643035061e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[6]/div/div/div/h1/span[3]/span</value>
      <webElementGuid>cf7ee5e8-d76b-466f-8007-f8e802920a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle'])[1]/following::span[2]</value>
      <webElementGuid>7834f979-9229-4ac8-9e49-f436cadda7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ramadhan'])[1]/following::span[2]</value>
      <webElementGuid>ddea51db-4370-428d-a129-ad6f7264aee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Family Name'])[1]/preceding::span[1]</value>
      <webElementGuid>4df77354-8b5b-4baf-90b7-041f7a7da82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='rama']/parent::*</value>
      <webElementGuid>509905db-9b52-42bd-a597-45e1ada3cd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span</value>
      <webElementGuid>2c327539-9ab4-4360-8857-adb8c007900d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                                rama
                            ' or . = '
                                rama
                            ')]</value>
      <webElementGuid>2ffbd136-5d76-4e92-962b-d3b493c86ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
