<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_70 (1)</name>
   <tag></tag>
   <elementGuidId>52997d19-116d-4510-ab9e-2ad7cf6bccfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr1661']/div[2]/latestobsforconceptlist/ul/li/div/span[2]/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Weight (kg): 70 today&quot;i >> internal:role=strong</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>22b3a2ba-970f-4b9e-87c7-5a1586112348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>eda7e449-227d-40e5-869b-f0943c7d5e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>5b1b4c2e-83c6-4942-ba55-a1e76b2a694c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr1661&quot;)/div[@class=&quot;info-body&quot;]/latestobsforconceptlist[@class=&quot;ng-isolate-scope&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/div[1]/span[2]/strong[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>5ecfce26-f77f-43b8-847f-4b2d2aa5b137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr1661']/div[2]/latestobsforconceptlist/ul/li/div/span[2]/strong</value>
      <webElementGuid>0b67d88a-22c6-4297-ad0c-f65334d3833b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LATEST OBSERVATIONS'])[1]/following::strong[1]</value>
      <webElementGuid>93d3ca95-5fdb-4c85-8d1b-1ab90b3b4c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/preceding::strong[1]</value>
      <webElementGuid>df698608-3677-456f-8165-9f2dc62bfc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='70']/parent::*</value>
      <webElementGuid>f179e777-40e7-4144-91eb-cd6471404002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>55398986-9460-4a3d-be4b-1e1b7d10eec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '70' or . = '70')]</value>
      <webElementGuid>d9b9a041-a08b-41f9-9430-cbe3454ba380</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
