<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_27 (1)</name>
   <tag></tag>
   <elementGuidId>cfe3f5a9-acf7-499e-b6d1-f7c0c763a80e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr1661']/div[2]/latestobsforconceptlist/ul/li[3]/div/span[2]/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#coreapps-fr1661 >> internal:text=&quot;27&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>9ac3b512-31b0-44dd-bd7a-65bc7fb69363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a8a7ac68-7224-4684-b747-33eddc70cf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>1dfded81-e685-4625-9351-b9bf8d5e4e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr1661&quot;)/div[@class=&quot;info-body&quot;]/latestobsforconceptlist[@class=&quot;ng-isolate-scope&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/div[1]/span[2]/strong[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>8e79e6d2-94c9-4485-a306-1ca06aa32b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr1661']/div[2]/latestobsforconceptlist/ul/li[3]/div/span[2]/strong</value>
      <webElementGuid>20a58402-86d1-4b86-b402-b85161bae821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[2]/following::strong[1]</value>
      <webElementGuid>a09fc453-b200-446d-ba1b-a68f72f12823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[3]/preceding::strong[1]</value>
      <webElementGuid>fd01f36c-69cf-4590-9df5-06f7accb2163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='27']/parent::*</value>
      <webElementGuid>f67001d4-00bb-4a8b-9f22-46a1da05dc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span[2]/strong</value>
      <webElementGuid>c3646ca9-c37f-45cd-90d2-724907ef38ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '27' or . = '27')]</value>
      <webElementGuid>668f04bd-ac22-46ba-8661-f68bb7160b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
