<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_100</name>
   <tag></tag>
   <elementGuidId>38e6ccfa-0ef6-4f59-8f4c-d67f9ac641a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='coreapps-fr2146']/div[2]/latestobsforconceptlist/ul/li[4]/div/span[2]/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#coreapps-fr2146 >> internal:text=&quot;100&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>f99660ad-4adb-4444-9568-5abdb0d68fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>9ba5fbce-042f-4406-b1c2-ebe9dbc778e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b186d0a1-176e-4f1f-984e-4f7a1e58b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;coreapps-fr2146&quot;)/div[@class=&quot;info-body&quot;]/latestobsforconceptlist[@class=&quot;ng-isolate-scope&quot;]/ul[1]/li[@class=&quot;ng-scope&quot;]/div[1]/span[2]/strong[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>be6c9519-0ef0-4945-b7f3-277df6b2ff84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coreapps-fr2146']/div[2]/latestobsforconceptlist/ul/li[4]/div/span[2]/strong</value>
      <webElementGuid>fdb86a51-a719-4d07-a2ac-a222f9e9b0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[3]/following::strong[1]</value>
      <webElementGuid>53e628e9-7b0d-4e4b-9141-97b15fcf747d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[4]/preceding::strong[1]</value>
      <webElementGuid>800cf616-1553-4d46-a20f-223e13450a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100']/parent::*</value>
      <webElementGuid>7ee92f67-9c27-4880-b59a-410c88031cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span[2]/strong</value>
      <webElementGuid>4981ff00-ee66-4bf5-a2c2-4d74e531eae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = '100' or . = '100')]</value>
      <webElementGuid>0c0e63f8-fde8-4fcd-864a-dd7affa5f877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
