<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Date</name>
   <tag></tag>
   <elementGuidId>96164b05-e8d2-4e28-9a2e-70b6cf0983b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.column-header.ng-binding.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='obsTable']/thead/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>dc4ba2ea-8618-40ba-9266-ee267a166483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>column in $ctrl.output.headers track by $index</value>
      <webElementGuid>eca952a3-45a2-464b-9bb1-ce4adf3ad122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>column-header ng-binding ng-scope</value>
      <webElementGuid>708b71c3-d084-480f-983a-6207bf81bf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date</value>
      <webElementGuid>f846ff3b-5907-4467-be78-e1ccfafe688b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;obsTable&quot;)/thead[1]/tr[@class=&quot;ng-scope&quot;]/th[@class=&quot;column-header ng-binding ng-scope&quot;]</value>
      <webElementGuid>bddbf46b-8eef-45f1-b9e5-4a7f82bf2b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='obsTable']/thead/tr/th</value>
      <webElementGuid>3d7055d1-74ef-42a8-a9b5-673b83ba7e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEALTH TREND SUMMARY'])[1]/following::th[1]</value>
      <webElementGuid>5f15325b-6340-417a-a124-f7d1888c4f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/following::th[1]</value>
      <webElementGuid>824b8045-9f42-4d44-ad53-8356f9708dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HR'])[1]/preceding::th[1]</value>
      <webElementGuid>6ed32f46-42b0-4e9b-ad70-07e19db2122d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Temp (c)'])[1]/preceding::th[2]</value>
      <webElementGuid>b6b74ef6-eac1-4def-8034-91ba9ff6f1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Date']/parent::*</value>
      <webElementGuid>a0e244a9-2126-4500-a3fa-ab6956b35a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>59c8c697-dcc1-4534-9ca8-facf220a9cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Date' or . = 'Date')]</value>
      <webElementGuid>d9e1c5f7-d627-4483-b96a-41c34d6b07c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
