<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pharmacy</name>
   <tag></tag>
   <elementGuidId>2af1413a-09d6-41bf-8ff1-3d6bb50ba525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='selected-location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selected-location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3b50d29-37ea-47bf-be2c-ac0a219351bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selected-location</value>
      <webElementGuid>ef0a5751-7ac9-436b-bd56-0cb36749f3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: text</value>
      <webElementGuid>8d2d1694-a50a-4f7e-b03c-e7c3c5cb0fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>location-uuid</name>
      <type>Main</type>
      <value>7f65d926-57d6-4402-ae10-a5b3bcbf7986</value>
      <webElementGuid>90931ec3-9e2c-4d60-a9b7-094f9239d650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pharmacy</value>
      <webElementGuid>fc024556-0fbb-4b96-9cc8-89d77e05c1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selected-location&quot;)</value>
      <webElementGuid>5e3920bd-8166-4d22-8ded-5d9906c2f656</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='selected-location']</value>
      <webElementGuid>f162ef9f-578b-4adc-aa8e-21de79a3d5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li[2]/a/span</value>
      <webElementGuid>320903d4-417a-4864-a5de-3a6a72a8c849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::span[1]</value>
      <webElementGuid>b84dbb82-231c-417d-8701-3e6118a60eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[1]</value>
      <webElementGuid>7a4f811a-a4bc-4163-aa44-520b450e3255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inpatient Ward'])[1]/preceding::span[1]</value>
      <webElementGuid>ec7c6b11-baa3-4fa0-b01c-f92d0b240108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pharmacy']/parent::*</value>
      <webElementGuid>355d32e0-ec2c-4517-a659-1ab1a459f38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>beb95132-e7c0-4887-9a8b-9588e0605b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'selected-location' and (text() = 'Pharmacy' or . = 'Pharmacy')]</value>
      <webElementGuid>c363d0db-12b6-467f-ba65-aaab53397048</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
