<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_You must choose a location</name>
   <tag></tag>
   <elementGuidId>231975a4-a2c0-490f-ab55-d7df5672349e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='sessionLocationError']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sessionLocationError</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6c7c167-8bae-4b0b-a42f-8a43cbe82557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>location-error</value>
      <webElementGuid>e1264cc9-5cf0-4fa2-a585-66843f5e931c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sessionLocationError</value>
      <webElementGuid>122b1d98-5277-4a37-a9ff-c052f900f323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You must choose a location!</value>
      <webElementGuid>1d996cfe-9c6f-46dc-89c4-662aa908a6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sessionLocationError&quot;)</value>
      <webElementGuid>0b1905d3-2b86-40a8-9900-0a59fd0b59bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='sessionLocationError']</value>
      <webElementGuid>d0b6317c-f9fc-44f3-a4f3-b952eae13966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/p[3]/label/span</value>
      <webElementGuid>b2d24446-0786-46ce-b61a-f92253b3cf8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::span[1]</value>
      <webElementGuid>901f6788-2fc5-4f1d-9d8e-d143eba8192e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inpatient Ward'])[1]/preceding::span[1]</value>
      <webElementGuid>b7d8562c-3b2a-4b7c-8e72-aa89248474ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isolation Ward'])[1]/preceding::span[1]</value>
      <webElementGuid>3889a90f-9381-4ad1-9682-657dac4b5560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You must choose a location!']/parent::*</value>
      <webElementGuid>ea68e0cd-6a42-40e0-8891-eb1cb1f75233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>596a900e-e046-4d37-b5cc-773ca6a36d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'sessionLocationError' and (text() = 'You must choose a location!' or . = 'You must choose a location!')]</value>
      <webElementGuid>ef8f9c4b-6170-4c6f-845a-54db5d6c7f39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
